import { type Metadata } from 'next';
import { ClerkProvider, SignedIn, UserButton } from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { TanStackQueryProvider } from '@/global/providers';
import { PrefetcProducts } from '@/services/prefetch';
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from '@tanstack/react-query';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // prefetch products
  const client = new QueryClient();
  await PrefetcProducts(client);

  return (
    <ClerkProvider>
      <html suppressHydrationWarning lang="en">
        <body
          suppressHydrationWarning
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <TanStackQueryProvider>
            <HydrationBoundary state={dehydrate(client)}>
              {children}
            </HydrationBoundary>
          </TanStackQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
